apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bff
  name: bff
spec:
  ports:
  - name: "4001"
    port: 4001
    protocol: TCP
    targetPort: 4001
  selector:
    app: bff
  type: ClusterIP
status:
  loadBalancer: {}
